### ISSUE TITLE
License is not listed

### ISSUE THREAD

**Issue by alice-i-cecile** [Jeff425/bevy_h264#1]
Please add a LICENSE.md file to your crate :) If you would like it to remain proprietary, feel free to state that explicitly in your README.

Might also be good to comment on the [patent situation](https://www.reddit.com/r/linux/comments/10v3op0/which_year_should_we_treat_h264_patents_as/) involved: users should at least know that this is messy.

**Comment by Jeff425** [comment]
Appreciate it, I knew I forgot something
